version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    container_name: brisapix-api-app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on: 
      - db

  db:
    build: .docker/postgres
    container_name: brisapix-api-db
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=brisapix
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data